-- Written by Rabia Alhaffar in 5/September/2020
-- icecreamboy assets manager
function load_assets()
  cone          = rl.LoadTexture("resources/images/cone.png")
  ball          = rl.LoadTexture("resources/images/ball.png")
  street        = rl.LoadTexture("resources/images/street.png")
  raylua        = rl.LoadTexture("resources/images/raylua.png")
  heart         = rl.LoadTexture("resources/images/heart.png")
  money_image   = rl.LoadTexture("resources/images/money.png")
  money_sound   = rl.LoadSound("resources/audio/money.wav")
  select_sound  = rl.LoadSound("resources/audio/select.wav")
  lose_sound    = rl.LoadSound("resources/audio/lose.wav")
  add_sound     = rl.LoadSound("resources/audio/add.wav")
  addball_sound = rl.LoadSound("resources/audio/select2.wav")
end

function unload_assets()
  rl.UnloadTexture(cone)
  rl.UnloadTexture(ball)
  rl.UnloadTexture(street)
  rl.UnloadTexture(raylua)
  rl.UnloadTexture(heart)
  rl.UnloadTexture(money_image)
  rl.UnloadSound(money_sound)
  rl.UnloadSound(select_sound)
  rl.UnloadSound(lose_sound)
  rl.UnloadSound(add_sound)
  rl.UnloadTexture(man1.happy)
  rl.UnloadTexture(man1.normal)
  rl.UnloadTexture(man1.sad)
  rl.UnloadTexture(girl1.happy)
  rl.UnloadTexture(girl1.normal)
  rl.UnloadTexture(girl1.sad)
  rl.UnloadSound(addball_sound)
end